import type { Config } from "tailwindcss";

const config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx,js}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    screens: {
      'small': '650px',
      'homewidth': '1200px',
      'browsewidth': '820px',
      'navwidth': '780px',
      'lg': '1080px',
      'filterlg': '1200px',
      'tablet': '700px',
      'filtertablet': '900px'
    },
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      translate: {
        '250': '220px',
        '4.5': '18px',
      },
      transitionDuration: {
        '250': '250ms',
        '150': '150ms',
      },
      scale: {
        '103': '1.02',
        '86': '0.88',
        '120': '1.20',
      },
      gridTemplateColumns: {
        'autofit': 'repeat(auto-fit, minmax(400px, 1fr))',
      },
      ringWidth: {
        '0.5': '0.5px',
        '3': '3px',
      },
      padding: {
        '4.5': '18px',
        '19': '70px',
        'topper': '1em',
      },
      brightness: {
        90: '.85',
        80: '.75',
      },
      spacing: {
        'restscreen': '95.2vh',
        'carouselsize': '1200px',
      },
      colors: {
        'midnight': '#141618',
        'offwhite': '#EFEFEF',
        'greyish': '#c9c9c9',
        'grey': '#7f7f7f',
        'lightmidnight': '#27272a',
        'blue': '#1E90FF',
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      margin: {
        'half': '50%',
        'main': '920px',
        '0.75': '3px',
        'showfilter': '250px',
        'topper': '0.45em',
        'linemargin': '1.8em',
        'seperate': '1.4em',
        'pricesmargin': '1.2em',
        'em': '0.15em',
        'em1': '0.25em',
        'responsivemargin': '14%',
        '7.5': '30px',
        '2.3': '6px',
        '22': '84px',
        '19': '76px',
        '18': '72px',
        '13': '52px',
        '4.5': '18px',
        '9': '38px',
        '0.3': '1px',
        '4.5px': '4.5px',
        'overlay': '1044px',
        'searchmargin': '21vh',
        'top': '0.45em',
      },
      height: {
        'cardimage': '66%',
        '4.5': '18px',
        'carousel': '1200px',
        'popup': '12vh',
        'line': '2em',
        'search': '2.2rem',
        'logos': '2em',
        'searchbox': '4vh',
        '70': '290px',
        '5.5': '22px',
        'card': '300px',
      },
      width: {
        'main': '1000px',
        '18': '68px',
        '80%': '85%',
        'showfilter': '100%',
        'filters': '250px',
        '0.4': '1.5px',
        '0.2': '0.5px',
        '4.5': '18px',
        '30': '120px',
        '100': '550px',
        'card': '100%',
        '34%': '365px',
        '100%': '100%',
        '26': '100px',
        '38': '164px',
        'carousel': '700px',
        'half': '50%',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        'box': '0.2rem',
        '4xl': '3rem',
        'searchbox': '0.6rem',
        'popup': '0.4rem',
        'carousel': '2rem',
      },
      keyframes: {
        slideright: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        slideleft: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        slideup: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        slidedown: {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(100%)' },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        slideup: 'slideup 0.2s ease-out forwards',
        slidedown: 'slidedown 0.2s ease-out forwards',
        slideout: 'slideright 0.2s ease-out forwards',
        slideback: 'slideleft 0.2s ease-out forwards',
      },
    },
    fontFamily: {
      azosans: ["azosans", "sans-serif"],
      galvji: ["galvji", "sans-serif"],
      inter: ["inter", "sans-serif"],
      roboto: ["roboto", "sans-serif"],
      interbold: ["interbold", "sans-serif"],
      interlight: ["interlight", "sans-serif"],
    },
    fontSize: {
      'filter': '1.5em',
      'pricerange': '0.85em',
      sm: '0.8rem',
      base: '1em',
      'filter': '1.08rem',
      'search': '2.0vh',
      'prices': '1.08em',
      xl: '1.1em',
      '2xl': '1.2em',
      'xll': '1.8em',
      '3xl': '2.08rem',
      '4xl': '2.441rem',
      '5xl': '3.052rem',
      'header': '1.8rem',
      'title': '3.6em',
    }
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
